### ISSUE TITLE
Copy binary file contents?

### ISSUE THREAD

**Issue by sxyazi** [AnirudhG07/plugins-yazi#1]
Does [copy-file-contents.yazi](https://github.com/AnirudhG07/plugins-yazi/tree/main/copy-file-contents.yazi) plan to support copying binary file contents, or is it just for copying text content? 

If that's the case, [`ya.clipboard()`](https://yazi-rs.github.io/docs/plugins/utils#ya.clipboard) would be a better implementation. It checks for available clipboard tools and calls them, supporting OSC 52, which means it would work over remote SSH. It also sets Yazi's internal clipboard buffer for use in other features, like pasting by pressing `p` in the input component.

**Comment by AnirudhG07** [comment]
hi @sxyazi, I am sorry but I have no clue why I haven't seen this issue. Yeah I would like binary file copying as well.
I'll look into this as you mentioned. Thanks so much for the suggestion

**Comment by AnirudhG07** [comment]
Please review the PR, I am still unable to copy the contents of a binary file. It works just fine on any other file.

**Comment by sxyazi** [comment]
Sorry, I didn't make myself clear. 

What I meant was, if there's no plan to support copying binary in the future, then `ya.clipboard()` is the better implementation. `ya.clipboard()` can only be used to copy text.

**Comment by AnirudhG07** [comment]
aah. lol. I totally misinterpreted this! my bad.
But the current version also doesnt copy binary files... I am not able to do it anyway

**Comment by AnirudhG07** [comment]
Now that you mention it, I dont think I want to enable binary file copying. I dont think anyone would want to copy file contents of any binary file. They can just open it in EDITOR and copy it the usual way.
If later on if I get a feature request for this. Then maybe I'll think about it again.

Do you know of anyway to copy binary file content directly from yazi? Maybe I can set it as an optional argument to allow binary file.

**Comment by sxyazi** [comment]
Ah I see. I don't need the binary copy feature, I was just saying that if it's not planned to be supported, it could be better implemented using `ya.clipboard`. Thanks for considering it!
